version: '3.8'

services:
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/notification
      - JWT_SECRET=secret35
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq

  ws:
    build:
      context: .
      dockerfile: Dockerfile.ws
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/notification
      - JWT_SECRET=secret35
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq

volumes:
  mongo-data:
